language: objective-c
xcode_project: Attributed.xcodeproj
xcode_scheme: Attributed-OSX
osx_image: xcode8.1
before_install: true
install: true
git:
  submodules: false
script:
  - xcodebuild -project Attributed.xcodeproj -scheme Attributed-OSX build test
